import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import StoreProvider from "../redux/storeProvider";
import AddBlogButton from "./components/AddBlogButton";
import AddBlogModal from "./components/AddBlogModal";
 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {




  return (
    <StoreProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-screen m-0 p-0`}
        >
          <Navbar />
          {children}
          <AddBlogModal />
          <AddBlogButton />
          
        </body>
      </html>
    </StoreProvider>
  );
}
